language: java

script: mvn clean install test -pl benayn-ustyle-test -Dtest=Me5Test -X

jdk:
  - oraclejdk6
  - openjdk6
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      - furonglang@gmail.com

branches:
  only:
    - master
