language: java

script: mvn test -pl benayn-ustyle-test -Dtest=Me5Test

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      - furonglang@gmail.com

branches:
  only:
    - master
